apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zipwi5y4g-dotnet-basic
  janus-idp.io/tekton: zipwi5y4g-dotnet-basic
  backstage.io/kubernetes-id: zipwi5y4g-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zipwi5y4g-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
